# Generated by Django 3.0.3 on 2020-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='mac',
            field=models.CharField(default=23123123123, max_length=17),
            preserve_default=False,
        ),
    ]
