# Generated by Django 3.0.3 on 2020-02-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0002_auto_20200224_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_online',
        ),
    ]
