# Generated by Django 3.0.3 on 2020-02-24 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0003_remove_client_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
