# Generated by Django 3.0.3 on 2020-02-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0004_client_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commands',
            new_name='Command',
        ),
    ]
