# Generated by Django 3.0.3 on 2020-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0005_auto_20200224_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
