# Generated by Django 3.0.3 on 2020-02-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0006_command_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('has_error', models.BooleanField(default=False)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corona.Command')),
            ],
        ),
    ]
