# Generated by Django 3.0.3 on 2020-02-24 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0007_commandresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
