# Generated by Django 3.0.3 on 2020-02-24 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0008_command_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandresult',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandresult',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
