# Generated by Django 3.0.7 on 2020-06-14 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('corona', '0009_auto_20200224_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='command',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.IntegerField(choices=[(0, 'Shell command'), (1, 'Module command')], default=0),
        ),
    ]
