# Generated by Django 3.2.8 on 2021-11-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0010_auto_20200614_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandresult',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='client',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandresult',
            name='command',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='corona.command'),
        ),
        migrations.AlterField(
            model_name='commandresult',
            name='has_error',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='commandresult',
            name='result',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
